export const wheelElement = document.getElementById("wheel") as SVGGElement | null;
export const tickSoundTemplate = document.getElementById("tickSound") as HTMLAudioElement | null;
export const input = document.getElementById("nameInput") as HTMLInputElement;
export const addBtn = document.getElementById("addBtn") as HTMLButtonElement || null;
export const list = document.getElementById("nameList") as HTMLUListElement;
export const getRemoveBtn = () => list.querySelectorAll(".btn-remove") as NodeListOf<HTMLButtonElement>;
export const errorHint = document.getElementById("errorHint") as HTMLParagraphElement;
export const emptyHint = document.getElementById("emptyHint") as HTMLParagraphElement;
export const drumrollAudio = document.getElementById("drumroll") as HTMLAudioElement | null;
export const multiplierSlider = document.getElementById("multiplierSlider") as HTMLInputElement;
export const multiplierValue = document.getElementById("multiplierValue") as HTMLSpanElement | null;
export const spinLeftBtn = document.getElementById("spin-left-btn") as HTMLButtonElement | null;
export const spinRightBtn = document.getElementById("spin-right-btn") as HTMLButtonElement | null;
export const shareBtn = document.getElementById("shareBtn") as HTMLButtonElement | null;
export const inventoryBtn = document.getElementById("inventoryBtn") as HTMLButtonElement;
export const inventoryCloseBtn = document.getElementById("inventoryCloseBtn") as HTMLButtonElement;
export const inventoryModal = document.getElementById("inventoryModal") as HTMLDialogElement;